import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Cursor;

/**
 *
 * @author Kimberly 
 */
public class IncomePanel extends javax.swing.JPanel {

    /**
     * Creates new form IncomePanel
     */
    public IncomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgetPanel = new javax.swing.JPanel();
        incomeLabel = new javax.swing.JLabel();
        sourceOfIncomeLabel = new javax.swing.JLabel();
        incomeField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        incomePane = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();
        calendar = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        budgetPanel.setBackground(new java.awt.Color(255, 255, 255));
        budgetPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        incomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        incomeLabel.setText("Income");
        budgetPanel.add(incomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 40));

        sourceOfIncomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sourceOfIncomeLabel.setText("Source of Income:");
        budgetPanel.add(sourceOfIncomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 30));

        incomeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        budgetPanel.add(incomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 210, 30));

        amountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountLabel.setText("Amount:");
        budgetPanel.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 30));

        amountField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        budgetPanel.add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, 30));

        addButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        addButton.setBackground(new java.awt.Color(57, 255, 50));
        addButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        budgetPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 30));

        deleteButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        deleteButton.setBackground(new java.awt.Color(255, 51, 51));
        deleteButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.setToolTipText("Type in ");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        budgetPanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, 30));

        incomePane.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N

        incomeTable.setAutoCreateRowSorter(true);
        incomeTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        incomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source of Income ", "Amount", "Date"
            }
        ));
        incomeTable.setToolTipText("Double click to edit data");
        incomePane.setViewportView(incomeTable);

        budgetPanel.add(incomePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 490, 290));

        calendar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        calendar.setToolTipText("Select a date");
        calendar.setDecorationBackgroundColor(new java.awt.Color(51, 255, 255));
        budgetPanel.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 240, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Select Date:");
        budgetPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 100, 30));

        saveButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        saveButton.setBackground(new java.awt.Color(51, 255, 255));
        saveButton.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setToolTipText("Type in ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        budgetPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, 30));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/income_bg.jpg"))); // NOI18N
        budgetPanel.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-480, -340, 1380, 940));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        // Get the contents of the text field
        
        String textSource = incomeField.getText();
        String textAmount = amountField.getText();
        
        // Check if the text field is not empty
        
        if (!textSource.isEmpty()&& !textAmount.isEmpty())
        {
            // Create a new row with the text as data
            String [] rowData = {textSource, textAmount};
            
            // Add the row to the table
            DefaultTableModel model = (DefaultTableModel) incomeTable.getModel();
            
            model.addRow(rowData);
             
             // Clear the text fields
            incomeField.setText("");
            amountField.setText("");
        } else {
        // Display an error message
        JOptionPane.showMessageDialog(this, "Please enter text in both fields.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Get the selected row index
        int selectedRowIndex = incomeTable.getSelectedRow();

        // Check if a row is selected
        if (selectedRowIndex != -1) {
            // Show a confirmation dialog to confirm the deletion
            int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this row?", "Confirmation", JOptionPane.YES_NO_OPTION);

            // Check if the user confirmed the deletion
            if (confirmation == JOptionPane.YES_OPTION) {
                // Get the table model
                DefaultTableModel model = (DefaultTableModel) incomeTable.getModel();

                // Remove the selected row from the table
                model.removeRow(selectedRowIndex);

                // Clear the text fields
                incomeField.setText("");
                amountField.setText("");
            }
        } else {
            // Display an error message
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
//GEN-LAST:event_deleteButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JPanel budgetPanel;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField incomeField;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JScrollPane incomePane;
    private javax.swing.JTable incomeTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sourceOfIncomeLabel;
    // End of variables declaration//GEN-END:variables
}
