/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Cursor;

/**
 *
 * @author Kimberly 
 */
public class IncomePanel extends javax.swing.JPanel {

    /**
     * Creates new form IncomePanel
     */
    public IncomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgetPanel = new javax.swing.JPanel();
        incomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtSrc = new javax.swing.JTextField();
        jAmt = new javax.swing.JLabel();
        jTxtAmt = new javax.swing.JTextField();
        jAddButton = new javax.swing.JButton();
        jDelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jIncomeTable = new javax.swing.JTable();
        calendar = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();

        budgetPanel.setBackground(new java.awt.Color(255, 255, 255));
        budgetPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        incomeLabel.setFont(new java.awt.Font("Sinhala MN", 2, 18)); // NOI18N
        incomeLabel.setText("Income");
        budgetPanel.add(incomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 50));

        jLabel1.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N
        jLabel1.setText("Source of Income ");
        budgetPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 30));
        budgetPanel.add(jTxtSrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 210, 30));

        jAmt.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N
        jAmt.setText("Amount");
        budgetPanel.add(jAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 30));
        budgetPanel.add(jTxtAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, 30));

        jAddButton.setBackground(new java.awt.Color(51, 255, 204));
        jAddButton.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N
        jAddButton.setText("ADD");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });
        budgetPanel.add(jAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 90, 30));

        jDelButton.setBackground(new java.awt.Color(255, 51, 51));
        jDelButton.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N
        jDelButton.setText("DELETE");
        jDelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDelButtonActionPerformed(evt);
            }
        });
        budgetPanel.add(jDelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, 30));

        jScrollPane1.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N

        jIncomeTable.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N
        jIncomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source of Income ", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jIncomeTable);
        if (jIncomeTable.getColumnModel().getColumnCount() > 0) {
            jIncomeTable.getColumnModel().getColumn(1).setResizable(false);
        }

        budgetPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 490, 290));

        calendar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        calendar.setToolTipText("Select a date");
        calendar.setDecorationBackgroundColor(new java.awt.Color(105, 255, 222));
        budgetPanel.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 330, 190));

        jLabel2.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N
        jLabel2.setText("Calendar");
        budgetPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        // TODO add your handling code here:
        // Get the contents of the text field
        
        String textSource = jTxtSrc.getText();
        String textAmount = jTxtAmt.getText();
        
        // Check if the text field is not empty
        
        if (!textSource.isEmpty()&& !textAmount.isEmpty())
        {
            // Create a new row with the text as data
            String [] rowData = {textSource, textAmount};
            
            // Add the row to the table
            DefaultTableModel model = (DefaultTableModel) jIncomeTable.getModel();
            
            model.addRow(rowData);
             
             // Clear the text fields
            jTxtSrc.setText("");
            jTxtAmt.setText("");
        } else {
        // Display an error message
        JOptionPane.showMessageDialog(this, "Please enter text in both fields.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jDelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelButtonActionPerformed
       // Get the contents of the text fields
    String textSource = jTxtSrc.getText();
    String textAmount = jTxtAmt.getText();
    
    // Check if the text fields are not empty
    if (!textSource.isEmpty() && !textAmount.isEmpty()) {
        // Get the table model
        DefaultTableModel model = (DefaultTableModel) jIncomeTable.getModel();
        
        // Loop through the rows of the table
        for (int i = 0; i < model.getRowCount(); i++) {
            // Get the text in the source and amount columns of the current row
            String sourceText = (String) model.getValueAt(i, 0);
            String amountText = (String) model.getValueAt(i, 1);
            
            // Check if both source and amount match the text fields
            if (sourceText.equals(textSource) && amountText.equals(textAmount)) {
                // Remove the current row from the table
                model.removeRow(i);
                
                // Decrement the row index to compensate for the removed row
                i--;
            }
        }
        
        // Clear the text fields
        jTxtSrc.setText("");
        jTxtAmt.setText("");
    } else {
        // Display an error message
        JOptionPane.showMessageDialog(this, "Please enter text in both fields.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    //GEN-LAST:event_jDelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel budgetPanel;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JButton jAddButton;
    private javax.swing.JLabel jAmt;
    private javax.swing.JButton jDelButton;
    private javax.swing.JTable jIncomeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAmt;
    private javax.swing.JTextField jTxtSrc;
    // End of variables declaration//GEN-END:variables
}
