import java.awt.Cursor;
import java.awt.Dimension;


/**
 *
 * @author Felicia
 */
public class MainGUI extends javax.swing.JFrame {
    DashboardPanel dashboardPanel = new DashboardPanel();
    IncomePanel incomePanel = new IncomePanel();
    ExpensesPanel expensesPanel = new ExpensesPanel();
    ReportPanel reportPanel = new ReportPanel();
    SettingsPanel settingsPanel = new SettingsPanel();
    
    /**
     * Creates new form BudgetGUI
     */
    public MainGUI() {
        initComponents();
        setVisible(true);
        contentPanel.add(dashboardPanel);  
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        menuButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        incomeButton = new javax.swing.JButton();
        expensesButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        dashboardButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(112, 0, 73));
        sidebarPanel.setAutoscrolls(true);
        sidebarPanel.setPreferredSize(new java.awt.Dimension(60, 600));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        menuButton.setBorderPainted(false);
        menuButton.setContentAreaFilled(false);
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 40));
        sidebarPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 59, 12));

        incomeButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        incomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transactions_36.png"))); // NOI18N
        incomeButton.setBorderPainted(false);
        incomeButton.setContentAreaFilled(false);
        incomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(incomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 60, 40));

        expensesButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        expensesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/manage_budget_36.png"))); // NOI18N
        expensesButton.setBorderPainted(false);
        expensesButton.setContentAreaFilled(false);
        expensesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensesButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(expensesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 60, 40));

        reportButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        reportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        reportButton.setBorderPainted(false);
        reportButton.setContentAreaFilled(false);
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(reportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 60, 40));

        incomeButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        dashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard.png"))); // NOI18N
        dashboardButton.setBorderPainted(false);
        dashboardButton.setContentAreaFilled(false);
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 60, 40));

        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void expensesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensesButtonActionPerformed
        contentPanel.removeAll();
        contentPanel.add(expensesPanel);
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_expensesButtonActionPerformed

    private void incomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeButtonActionPerformed
        contentPanel.removeAll(); // Remove any existing components from the content panel
        contentPanel.add(incomePanel);
        contentPanel.revalidate(); // Refresh the layout of the content panel
        contentPanel.repaint();
    }//GEN-LAST:event_incomeButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        contentPanel.removeAll(); // Remove any existing components from the content panel
        contentPanel.add(reportPanel);
        contentPanel.revalidate(); // Refresh the layout of the content panel
        contentPanel.repaint();
    }//GEN-LAST:event_reportButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // Toggle the sidebar panel's preferred size when the menu button is clicked
        if (sidebarPanel.getPreferredSize().width == 60) {
            sidebarPanel.setPreferredSize(new Dimension(200, 600));
        } else {
            sidebarPanel.setPreferredSize(new Dimension(60, 600));
        }
        // Repack the JFrame to adjust its size to the new preferred size of the sidebar panel
        revalidate();
        pack();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JButton expensesButton;
    private javax.swing.JButton incomeButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton reportButton;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
