import java.awt.Cursor;
import java.io.IOException;
import java.util.Date;

import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Felicia
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportLabel = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JCalendar();
        sortByLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        expenseButton = new javax.swing.JButton();
        categoryButton = new javax.swing.JButton();
        totalButton = new javax.swing.JButton();
        reportScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        reportLabel1 = new javax.swing.JLabel();
        differenceLabel = new javax.swing.JLabel();
        budgetLabel1 = new javax.swing.JLabel();
        actualSpentLabel1 = new javax.swing.JLabel();
        calculateDailyReportButton = new javax.swing.JButton();
        differenceField = new javax.swing.JTextField();
        budgetField = new javax.swing.JTextField();
        actualSpentField = new javax.swing.JTextField();
        populateReportTableButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        reportLabel.setText("Your Daily Report:");
        add(reportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 40));

        calendar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        calendar.setToolTipText("Select a date");
        calendar.setDecorationBackgroundColor(new java.awt.Color(51, 255, 255));
        add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 240, 150));

        sortByLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sortByLabel.setText("Sort by:");
        add(sortByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 60, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Select Date:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 100, 30));

        expenseButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        expenseButton.setBackground(new java.awt.Color(82, 252, 138));
        expenseButton.setText("Expense");
        expenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseButtonActionPerformed(evt);
            }
        });
        add(expenseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        categoryButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        categoryButton.setBackground(new java.awt.Color(49, 164, 255));
        categoryButton.setText("Category");
        categoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButtonActionPerformed(evt);
            }
        });
        add(categoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        totalButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        totalButton.setBackground(new java.awt.Color(251, 255, 50));
        totalButton.setText("Total");
        totalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalButtonActionPerformed(evt);
            }
        });
        add(totalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        reportScrollPane1.setFont(new java.awt.Font("Sinhala MN", 1, 14)); // NOI18N

        reportTable.setAutoCreateRowSorter(true);
        reportTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense", "Category", "Budget", "Actual Spent", "Difference"
            }
        ));
        CurrencyRenderer.formatCurrencyColumns(reportTable, 2, 3, 4);
        reportTable.setToolTipText("Double click to edit data");
        reportScrollPane1.setViewportView(reportTable);

        add(reportScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 490, 290));

        reportLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reportLabel1.setText("Report");
        add(reportLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 40));

        differenceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        differenceLabel.setText("Difference");
        add(differenceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, -1));

        budgetLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        budgetLabel1.setText("Budget");
        add(budgetLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        actualSpentLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actualSpentLabel1.setText("Actual Spent");
        add(actualSpentLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));

        calculateDailyReportButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        calculateDailyReportButton.setBackground(new java.awt.Color(51, 255, 255));
        calculateDailyReportButton.setText("Calculate");
        calculateDailyReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateDailyReportButtonActionPerformed(evt);
            }
        });
        add(calculateDailyReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        differenceField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        differenceField.setText("0");
        differenceField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(49, 137, 255)));
        differenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                differenceFieldActionPerformed(evt);
            }
        });
        add(differenceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 140, -1));

        budgetField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        budgetField.setText("0");
        budgetField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(57, 255, 50)));
        budgetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetFieldActionPerformed(evt);
            }
        });
        add(budgetField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 140, -1));

        actualSpentField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        actualSpentField.setText("0");
        actualSpentField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 48, 48)));
        actualSpentField.setCaretColor(new java.awt.Color(227, 215, 0));
        actualSpentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualSpentFieldActionPerformed(evt);
            }
        });
        add(actualSpentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 140, -1));

        populateReportTableButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        populateReportTableButton.setBackground(new java.awt.Color(51, 255, 255));
        populateReportTableButton.setText("Populate Table");
        populateReportTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateReportTableButtonActionPerformed(evt);
            }
        });
        add(populateReportTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void expenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseButtonActionPerformed

    private void categoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButtonActionPerformed
        
    }//GEN-LAST:event_categoryButtonActionPerformed

    private void totalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalButtonActionPerformed
        
    }//GEN-LAST:event_totalButtonActionPerformed

    private void differenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_differenceFieldActionPerformed
        
    }//GEN-LAST:event_differenceFieldActionPerformed

    private void actualSpentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualSpentFieldActionPerformed
    
    }//GEN-LAST:event_actualSpentFieldActionPerformed

    private void budgetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetFieldActionPerformed
    
    }//GEN-LAST:event_budgetFieldActionPerformed

    private void populateReportTableButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Get the selected date from the calendar
        Date selectedDate = calendar.getDate();
        ExpensesPanel expensesPanel = new ExpensesPanel();
    
        // Get the table model from the reportTable
        DefaultTableModel reportTableModel = (DefaultTableModel) reportTable.getModel();
        DefaultTableModel foodModel = (DefaultTableModel) expensesPanel.getFoodTable().getModel();
        DefaultTableModel entertainmentModel = (DefaultTableModel) expensesPanel.getEntertainmentTable().getModel();
        DefaultTableModel transportationModel = (DefaultTableModel) expensesPanel.getTransportationTable().getModel();
        DefaultTableModel housingModel = (DefaultTableModel) expensesPanel.getHousingTable().getModel();
        DefaultTableModel otherModel = (DefaultTableModel) expensesPanel.getOtherTable().getModel();
    
        try {
            Driver.importTable(entertainmentModel, Expense.expensesFolder, "entertainmentTable.txt", selectedDate);
            Driver.importTable(foodModel, Expense.expensesFolder, "foodTable.txt", selectedDate);
            Driver.importTable(transportationModel, Expense.expensesFolder, "transportationTable.txt", selectedDate);
            Driver.importTable(housingModel, Expense.expensesFolder, "housingTable.txt", selectedDate);
            Driver.importTable(otherModel, Expense.expensesFolder, "otherTable.txt", selectedDate);
        } catch (IOException e) {
            e.printStackTrace();
        }
    
        // Clear the reportTableModel before adding new data
        reportTableModel.setRowCount(0);
    
        // Populate the reportTableModel with data from each table model
        populateReportTable(reportTableModel, entertainmentModel, "Entertainment");
        populateReportTable(reportTableModel, foodModel, "Food");
        populateReportTable(reportTableModel, transportationModel, "Transportation");
        populateReportTable(reportTableModel, housingModel, "Housing");
        populateReportTable(reportTableModel, otherModel, "Other");
    
        // Set the reportTableModel as the model for the reportTable
        reportTable.setModel(reportTableModel);
    }
                                                             
    private void populateReportTable(DefaultTableModel reportTableModel, DefaultTableModel tableModel, String category) {
        // Loop through each row of the table model and extract the necessary information
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String expenseName = (String) tableModel.getValueAt(i, 0);
            double budget = Double.parseDouble((String) tableModel.getValueAt(i, 1));
            double actualSpent = Double.parseDouble((String) tableModel.getValueAt(i, 2));
            double difference = budget - actualSpent;
            
            // Add the extracted information as a new row in the reportTableModel
            reportTableModel.addRow(new Object[]{expenseName, category, budget, actualSpent, difference});
        }
    }

    private void calculateDailyReportButtonActionPerformed(java.awt.event.ActionEvent evt) {

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualSpentField;
    private javax.swing.JLabel actualSpentLabel1;
    private javax.swing.JTextField budgetField;
    private javax.swing.JLabel budgetLabel1;
    private javax.swing.JButton calculateDailyReportButton;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JButton categoryButton;
    private javax.swing.JTextField differenceField;
    private javax.swing.JLabel differenceLabel;
    private javax.swing.JButton expenseButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton populateReportTableButton;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JLabel reportLabel1;
    private javax.swing.JScrollPane reportScrollPane1;
    private javax.swing.JTable reportTable;
    private javax.swing.JLabel sortByLabel;
    private javax.swing.JButton totalButton;
    // End of variables declaration//GEN-END:variables
}
